"""empty message

Revision ID: c59661dd2097
Revises: 
Create Date: 2020-01-13 14:06:43.717138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59661dd2097'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.String(length=10), nullable=False),
    sa.Column('subreddit', sa.String(length=30), nullable=False),
    sa.Column('shortlink', sa.String(length=30), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('created_local', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('up_ratio', sa.Float(precision=10), nullable=True),
    sa.Column('nsfw', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('flair', sa.String(length=20), nullable=True),
    sa.Column('spoiler', sa.Boolean(), nullable=True),
    sa.Column('awards', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flair'),
    sa.UniqueConstraint('is_edited'),
    sa.UniqueConstraint('post_id'),
    sa.UniqueConstraint('up_ratio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
